services:
  pan_metrics:
    image: postgres:16
    container_name: pan_metrics
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
      PGTZ: ${PGTZ}
    ports:
      - "5433:5432"
    volumes:
      - db_data_pan_metrics:/var/lib/postgresql/data
      
  
volumes:
  db_data_pan_metrics:
