export const PROVIDERS = {
  LOGGED_USER_SERVICE: 'LOGGED_USER_SERVICE',
  PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
  JWT_SERVICE: 'JWT_SERVICE',
  USER_REPOSITORY: 'USER_REPOSITORY',
  CITY_REPOSITORY: 'CITY_REPOSITORY',
  STATE_REPOSITORY: 'STATE_REPOSITORY',
  ADDRESS_REPOSITORY: 'ADDRESS_REPOSITORY',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG_SERVICE',
  HASH_SERVICE: 'HASH_SERVICE',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  USER_PERMISSION_REPOSITORY: 'USER_PERMISSION_REPOSITORY',
  CASL_ABILITY_SERVICE: 'CASL_ABILITY_SERVICE',
};
