export const PROVIDERS = {
  ADDRESS_REPOSITORY: 'ADDRESS_REPOSITORY',
  ADDRESS_MAPPER: 'ADDRESS_MAPPER',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG_SERVICE',
  HASH_SERVICE: 'HASH_SERVICE',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  ROLE_MAPPER:'ROLE_MAPPER',
  STATE_MAPPER: 'STATE_MAPPER',
  CITY_MAPPER: 'CITY_MAPPER',
};
