#!/bin/bash

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

PATTERN="^(feat|fix|chore|docs|refactor|test|style):"

if ! echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then
  echo ""
  echo "❌ Erro: Mensagem de commit inválida."
  echo "O commit deve começar com:"
  echo "feat:, fix:, chore:, docs:, refactor:, test: ou style:"
  echo ""
  exit 1
fi

if [ ${#COMMIT_MSG} -gt 72 ]; then
  echo ""
  echo "❌ Erro: Mensagem de commit inválida."
  echo "O commit deve ter no maximo 72 catacteres"
  echo ""
  exit 1
fi

exit 0